### PR TITLE
CI-1281: Add support for configurable wal-dir to stolon

### PR DESCRIPTION
**Pull request by VSpike**
This commit adds a --wal-dir flag to the keeper.

The symlink to a new WAL disk needs to be created as part of the
database initialisation step, and also whenever we clobber the database,
such as when taking a pg_basebackup (if pg_rewind is
disabled/unavailable). By passing this directory as an argument to
initdb and pg_basebackup, we can cover all the scenarios that the keeper
erases and recreates the data directory, ensuring the symlink is always
present.

### CODE REVIEW

**Comment by dyson** [comment]
Rebased to resolve conflicts.

**Review by dyson — APPROVED** [review]
Retested after the rebase and everything LGTM.

**Comment by VSpike** [comment]
Thanks for doing the rebase!

**Comment by dyson** [comment]
No worries!

**Pull request merged**
